interface ProductInvoice {
  id?: number; // Assuming 'id' is autogenerated by the database
  number?: string;
  productId: number;
  quantity: number;
  price: number;
  currencyId: number;
  retailerId: number;
  date: Date;
}
