interface Product {
  id?: number; // Assuming 'id' is autogenerated by the database
  barcode: string;
  name: string;
  size?: string;
  weight: number;
  partNumbers: string[];
  threshold: number;
  code?: string;
  image?: string;
  images: string[];
  notes: string[];
  categoryId?: string;
  manufacturerId?: string;
  invoices: ProductInvoice[];
  storages: ProductStorage[];
}
